version: '3.9'

services:

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: task_management_system
      POSTGRES_USER: bestuser
      POSTGRES_PASSWORD: bestuser