jwt:
  secret: 92374JGJHG9837729374HH732
  lifetime: 30m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/task_management_system
    driver-class-name: org.postgresql.Driver
    username: bestuser
    password: bestuser

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 1
    repair-on-migrate: true
    validate-on-migrate: false
logging:
  level:
    org.flywaydb: DEBUG


