server:
  servlet:
    context-path: /api


jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/task_management_system
    driver-class-name: org.postgresql.Driver
    username: bestuser
    password: bestuser

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 1


