server:
  servlet:
    context-path: /api/tasks

jwt:
  secret: 92374JGJHG9837729374HH732
  lifetime: 30m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_system
    username: bestuser
    password: bestuser
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Pos