spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_system
    username: bestuser
    password: bestuser
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
