server:
  servlet:
    context-path: /api

jwt:
  secret: 92374JGJHG9837729374HH732
  lifetime: 30m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_system
    username: bestuser
    password: bestuser
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: public
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none

